trigger:
- master
- release/*

phases:
- template: ../templates/blazor-build.yml
  parameters:
    queueName: DotNetCore-Windows
    variables:
      SignType: real
      TeamName: AspNetCore
    beforeBuild:
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
      displayName: 'Run compliance check'
      inputs:
        targetType: F
    - task: MicroBuildSigningPlugin@1
      displayName: Install CodeSigning plugin
      inputs:
        signType: $(SignType)
        zipSources: false
      condition: and(succeeded(), in(variables['SignType'], 'test', 'real'))

    afterBuild:
    - task: MicroBuildCleanup@1
      displayName: Perform Cleanup Tasks
      condition: succeededOrFailed()
